### ISSUE TITLE
local variable 'nheigth' referenced before assignment

### ISSUE THREAD

**Issue by zxzhijia** [niektemme/tensorflow-mnist-predict#1]
Hi, thanks you for sharing. I ran the code. It gives me an error 

local variable 'nheigth' referenced before assignment

I run it by using:
(tensorflow)xu@xu-ThinkCentre-M72e:~ $ python Predict.py 'HandWrittenDigit2.png'
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "Predict.py", line 134, in <module>
    main(sys.argv[1])
  File "Predict.py", line 129, in main
    imvalue = imageprepare(argv)
  File "Predict.py", line 100, in imageprepare
    if (nheigth == 0): #rare case but minimum is 1 pixel
UnboundLocalError: local variable 'nheigth' referenced before assignment
(tensorflow)xu@xu-ThinkCentre-M72e:~ $ python Predict.py 'HandWrittenDigit2.png'
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "Predict.py", line 133, in <module>
    main(sys.argv[1])
  File "Predict.py", line 128, in main
    imvalue = imageprepare(argv)
  File "Predict.py", line 99, in imageprepare
    if (nheigth == 0): #rare case but minimum is 1 pixel
UnboundLocalError: local variable 'nheigth' referenced before assignment
(tensorflow)xu@xu-ThinkCentre-M72e:~ $

**Comment by zxzhijia** [comment]
it works now. Thank you again.

**Comment by htaptit** [comment]
Can you show me how to fix it ?

**Comment by chouex** [comment]
@htaptit it was just a typo error, change nheig**ht** to nheigth
