### ISSUE TITLE
variable name "nheigth"is wrong?

### ISSUE THREAD

**Issue by zealerww** [niektemme/tensorflow-mnist-predict#5]
Your work helps me, but i think the variable name "nheigth" is wrong , it should be "nheight". You can find it in line 76/77 of predict_1.py and line 116/117 of predict_2.py.

**Comment by ghost** [comment]
thanks for sharing. the code is full of errors.

**Comment by niektemme** [comment]
fixed

**Comment by atjiu** [comment]
好像还是没有修过来https://github.com/niektemme/tensorflow-mnist-predict/blob/master/predict_2.py#L117
